services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: 'app'
    restart: 'always'
    ports:
      - "80:8000"
    volumes:
      - type: 'bind'
        source: './'
        target: '/app'
    depends_on:
      - db

  db:
    image: postgres:17.0-alpine
    container_name: 'postgres_db'
    restart: 'always'
    expose:
      - 5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./dbdata:/var/lib/postgresql/data
